version: "3.8"

services:
  backend:
    build: ../backend
    container_name: log-analyzer-backend
    ports:
      - "5000:5000"
    networks:
      - log-analyzer

  frontend:
    build: ../frontend
    container_name: log-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - log-analyzer

networks:
  log-analyzer:
    driver: bridge

